config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  match '/ratings/article', to: 'ratings#article', via: :post
  match '/ratings/comment', to: 'ratings#comment', via: :post

  devise_for :users, path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  get 'welcome/index'
  resources :users, only: [:show, :index] do
    member do
      get :subscriptions, :subscribers
    end
  end
  resources :subscriptions

  root 'welcome#index'

  resources :articles do
    resources :comments
  end

  mount Sidekiq::Web, at: '/sidekiq'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
  belongs_to :user
  has_many :comment_ratings, dependent: :destroy
  validates :body, presence: true, :length => {:maximum => 500}
  scope :recent, lambda { order('created_at DESC') }

  def user_rating(user)
    user_rating = comment_ratings.find_by(user_id: user.id)
    user_rating ? user_rating.rating : 0
  end

  def rate!(user_id, rate)
    comment_rating = CommentRating.find_by(user_id: user_id, comment_id: id)
    if comment_rating
      if comment_rating.rating != 0
        new_rating = (rating - comment_rating.rating) + rate.to_i
      else
        new_rating = rating + rate.to_i
      end
      comment_rating.update_attribute(:rating, rate)
      update_attribute(:rating, new_rating)
    else
      CommentRating.create(user_id: user_id, comment_id: id, rating: rate)
      self.update_attribute(:rating, rating + rate.to_i)
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @article_id = params[:article_id]
    @article = Article.find(@article_id)
    @comments = @article.comments.order(:created_at => :desc).paginate(:page => params[:page], :per_page => 5)
    @comment = @article.comments.create(comment_params.merge!({:user_id => current_user.id}))
    if @comment.valid?
      redirect_to article_path(@article)
    else
      render 'articles/show'
      # redirect_to article_path(@article), alert: 'Your book was not found'
    end
  end

  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    authorize! :destroy, @comment
    if @comment.destroy
      render :json => {:success => true}
    elsif
      render :json => {:success => false}
    end
    # redirect_to article_path(@article)
  end

  private
  def comment_params
    params.require(:comment).permit(:commenter, :body)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<% if comment.body.present? %>
<div class="media delete-sweet-alert-wrapper">
  <hr/>
  <a class="pull-left" href="#">
    <%= image_tag comment.user.avatar.url(:medium), class: "media-object img-circle",
                  width: '64px', height: '64px',  alt: comment.user.get_name %>
  </a>
  <div class="media-body">
    <h4 class="media-heading">
      <%= comment.user.get_name %>
      <small>commented <%= time_ago_in_words(comment.created_at) %> ago</small>
      <div class="pull-right">
        <small>
        <% if can? :destroy, comment%>
            <%= link_to 'Delete', [comment.article, comment], #method: :delete,
                        # data: { confirm: 'Are you sure?' },
                        class: 'text-danger delete-sweet-alert' %>
        <% end %>
        </small>
      </div>
    </h4>
    <div class="embed">
      <%= comment.body %>
    </div>
    <%= render 'comments/rating_form', comment: comment %>
  </div>
</div>
<% end %>

app/views/comments/_form.html.erb
<div class="well">
  <h4>Leave a Comment:</h4>
  <%= form_for([@article, @article.comments.build]) do |f| %>
      <% if @comment.present? && @comment.errors.any? %>
          <p class="text-danger">
            <%= pluralize(@comment.errors.count, "error") %> prohibited
            this comment from being saved:
          <ul class="text-danger">
            <% @comment.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
          </p>
      <% end %>
      <div class="form-group">
        <%= f.text_area :body, {class: 'form-control', rows: '3'} %>
      </div>
      <%= f.submit 'Submit', :class => 'btn btn-primary' %>
  <% end %>
</div>

app/views/comments/_rate_down.html.erb
<%= form_for(comment, url: ratings_comment_url, method: :post, remote: true) do |f| %>
    <%= f.hidden_field :id %>
    <% if comment.user_rating(current_user) < 0 %>
        <%= f.hidden_field :rating, value: 0 %>
        <%= f.submit "", class: "rate_down rate-down-js" %>
    <% else %>
        <%= f.hidden_field :rating, value: -1 %>
        <%= f.submit "", class: "rate_down" %>
    <% end %>
<% end %>

app/views/comments/_rate_up.html.erb
<%= form_for(comment, url: ratings_comment_url, method: :post, remote: true) do |f| %>
    <%= f.hidden_field :id %>
    <% if comment.user_rating(current_user) > 0 %>
        <%= f.hidden_field :rating, value: 0 %>
        <%= f.submit "", class: "rate_up rate-up-js" %>
    <% else %>
        <%= f.hidden_field :rating, value: 1 %>
        <%= f.submit "", class: "rate_up" %>
    <% end %>
<% end %>

app/views/comments/_rating_form.html.erb
<% if user_signed_in? %>
    <div id="rate_comment_<%= comment.id %>" class="rating-wrap pull-right">
      <%= render 'comments/rate_up', comment: comment %>
      <% if comment.rating > 0 %>
          <span class="rating-container rating-green"><%= comment.rating %></span>
      <% elsif comment.rating < 0 %>
          <span class="rating-container rating-red"><%= comment.rating %></span>
      <% else %>
          <span class="rating-container"><%= comment.rating %></span>
      <% end %>
      <%= render 'comments/rate_down', comment: comment %>
    </div>
<% end %>