config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  match '/ratings/article', to: 'ratings#article', via: :post
  match '/ratings/comment', to: 'ratings#comment', via: :post

  devise_for :users, path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  get 'welcome/index'
  resources :users, only: [:show, :index] do
    member do
      get :subscriptions, :subscribers
    end
  end
  resources :subscriptions

  root 'welcome#index'

  resources :articles do
    resources :comments
  end

  mount Sidekiq::Web, at: '/sidekiq'

end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :article_ratings, dependent: :destroy
  validates :title, presence: true
  validates :text, presence: true, length: {maximum: 5000}
  validate :check_cruel_content
  scope :recent, lambda { order('created_at DESC') }

  @@cruel_words = [
      :bad,
      :sex,
      :boobs,
      :dick,
      :fuck
  ]

  def check_cruel_content
    @words = text.split(' ')
    @words.each do |word|
      if @@cruel_words.include?(word.to_sym)
        errors.add(:text, "can't contain cruel content")
        break
      end
    end
  end

  def user_rating(user)
    user_rating = article_ratings.find_by(user_id: user.id)
    user_rating ? user_rating.rating : 0
  end

  def rate!(user_id, rate)
    article_rating = ArticleRating.find_by(user_id: user_id, article_id: id)
    if article_rating
      if article_rating.rating != 0
        new_rating = (rating - article_rating.rating) + rate.to_i
      else
        new_rating = rating + rate.to_i
      end
      article_rating.update_attribute(:rating, rate)
      update_attribute(:rating, new_rating)
    else
      ArticleRating.create(user_id: user_id, article_id: id, rating: rate)
      self.update_attribute(:rating, rating + rate.to_i)
    end
  end

  def self.from_subscribing_users_by(user)
    subscribing_users_ids = 'SELECT author_id FROM subscriptions
                         WHERE subscriber_id = :user_id'
    where("user_id IN (#{subscribing_users_ids}) OR user_id = :user_id",
          user_id: user.id)
  end

  def self.search(search)
    if search
      where('title LIKE :search OR text LIKE :search', search: "%#{search}%")
    else
      where(nil)
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  respond_to :html

  def index
    if user_signed_in?
      @articles = current_user.feed.recent.search(params[:search]).paginate(:page => params[:page], :per_page => 10)
    else
      @articles = Article.all().recent.search(params[:search]).paginate(:page => params[:page], :per_page => 10)
    end
  end

  def show
    @article = Article.find(params[:id])
    # @comments = @article.comments.recent.paginate(:page => params[:page], :per_page => 5)
    @comments = @article.comments
  end

  def new
    @article = Article.new
  end

  def edit
    @article = Article.find(params[:id])
    authorize! :update, @article
  end

  def create
    @article = Article.new(article_params.merge!({:user_id => current_user.id}))
    if @article.save
      flash[:notice] = "The article has created successfully."
      send_new_article_notification(@article.id)
    end
    respond_with(@article)
  end

  def update
    @article = Article.find(params[:id])
    authorize! :update, @article
    if @article.update(article_params)
      flash[:notice] = "The article has updated successfully."
    end
    respond_with(@article)
  end

  def destroy
    @article = Article.find(params[:id])
    authorize! :destroy, @article
    if @article.destroy
      render :json => {:success => true}
    elsif
      render :json => {:success => false}
    end
  end

  private
  def article_params
    params.require(:article).permit(:title, :text)
  end

  def send_new_article_notification(article_id)
    NewArticleMailWorker.perform_async(article_id)
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_articles.html.erb
<%= render 'shared/pagination', items: @articles %>
<% for article in @articles %>
    <div class="delete-sweet-alert-wrapper">
      <hr/>
      <h2>
        <%= link_to article.title, article_path(article) %>
      </h2>

      <div class="pull-right">
        <% if user_signed_in? %>
            <% if can? :update, article %>
                <%= link_to 'Edit', edit_article_path(article), class: 'text-warning', role: 'button' %> |
            <% end %>
            <% if can? :destroy, article %>
                <%= link_to 'Delete', article_path(article), #method: :delete, data: { confirm: 'Are you sure?' },
                            class: 'text-danger delete-sweet-alert', role: 'button' %></td>
            <% end %>
        <% end %>
      </div>
      <p class="lead">
        by <a href="<%= user_path(article.user) %>"><%= article.user.get_name %></a>
      </p>

      <p>
        <small class="text-muted">
          Posted on <%= article.created_at.strftime("%B %e, %Y at %l:%M %p") %>
        </small>
        <small class="text-muted pull-right">
          Comments: <%= article.comments.count %>
        </small>
      </p>
      <%= truncate(article.text, :length => 500) %>
      </p>
      <%= link_to 'Read More', article_path(article), class: 'btn btn-primary' %>
      <%= render 'articles/rating_form', article: article %>
    </div>
<% end %>
<%= render 'shared/pagination', items: @articles %>

app/views/articles/_form.html.erb
<legend><%= article_form_legend %></legend>
<div class="well">
  <%= form_for @article, html: { class: 'form-horizontal'} do |f| %>
    <% if @article.errors.any? %>
        <p class="text-danger">
            <%= pluralize(@article.errors.count, "error") %> prohibited
            this article from being saved:
        <ul class="text-danger">
            <% @article.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
            </ul>
        </p>
    <% end %>
    <div class="form-group">
        <div class="col-sm-12">
            <%= f.text_field :title, {class: 'form-control', placeholder: 'Title'} %>
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-12">
        <%= f.text_area :text, {class: 'form-control', rows: '5'} %>
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-12">
            <%= f.submit 'Submit', :class => 'btn btn-primary' %>
        </div>
    </div>
<% end %>
</div>

app/views/articles/_rate_down.html.erb
<%= form_for(article, url: ratings_article_url, method: :post, remote: true) do |f| %>
    <%= f.hidden_field :id %>
    <% if article.user_rating(current_user) < 0 %>
        <%= f.hidden_field :rating, value: 0 %>
        <%= f.submit "", class: "rate_down rate-down-js" %>
    <% else %>
        <%= f.hidden_field :rating, value: -1 %>
        <%= f.submit "", class: "rate_down" %>
    <% end %>
<% end %>

app/views/articles/_rate_up.html.erb
<%= form_for(article, url: ratings_article_url, method: :post, remote: true) do |f| %>
    <%= f.hidden_field :id %>
    <% if article.user_rating(current_user) > 0 %>
        <%= f.hidden_field :rating, value: 0 %>
        <%= f.submit "", class: "rate_up rate-up-js" %>
    <% else %>
        <%= f.hidden_field :rating, value: 1 %>
        <%= f.submit "", class: "rate_up" %>
    <% end %>
<% end %>

app/views/articles/_rating_form.html.erb
<% if user_signed_in? %>
    <div id="rate_article_<%= article.id %>" class="rating-wrap pull-right">
      <%= render 'articles/rate_up', article: article %>
      <% if article.rating > 0 %>
          <span class="rating-container rating-green"><%= article.rating %></span>
      <% elsif article.rating < 0 %>
          <span class="rating-container rating-red"><%= article.rating %></span>
      <% else %>
          <span class="rating-container"><%= article.rating %></span>
      <% end %>
      <%= render 'articles/rate_down', article: article %>
    </div>
<% end %>

app/views/articles/edit.html.erb
<%= render 'form',  :article_form_legend => t('update_article') %>
<%= link_to 'Back', articles_path, class: 'btn btn-default' %>

app/views/articles/index.html.erb
<h1>Listing articles</h1>

<% if user_signed_in? %>

<% end %>
<div style="margin-bottom: 10px">
  <%= form_tag articles_path, :method => :get, :remote => false, :id => "articles_search" do %>
    <div class="row">
      <div class="col-lg-6">
        <div class="input-group">
          <%= text_field_tag :search, params[:search], class: 'form-control', placeholder: 'Search' %>
          <span class="input-group-btn">
            <%= submit_tag "Search", :name => nil, :class => "btn btn-default" %>
          </span>

        </div>
      </div>
    </div>
  <% end %>
</div>
<div id="articles">
  <%= render 'articles' %>
</div>

app/views/articles/index.js.erb
$("#articles").html("<%= escape_javascript(render('articles')) %>");

app/views/articles/new.html.erb
<%= render 'form',  :article_form_legend => t('new_article') %>
<%= link_to 'Back', articles_path, class: 'btn btn-default' %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>
<p class="lead">
  by <a href="#"><%= @article.user.get_name %></a>
</p>
<hr>
<p class="text-muted"> Posted on <%= @article.created_at.strftime("%B %e, %Y at %l:%M %p") %></p>
<%= link_to 'Back', articles_path, class: 'btn btn-default' %>
<% if user_signed_in? %>
    <% if can? :update, @article %>
        <%= link_to 'Edit', edit_article_path(@article), class: 'btn btn-warning' %>
    <% end %>
<% end %>
<hr>
<div class="embed">
  <%= @article.text %>
</div>
<%= render 'rating_form', article: @article %>
<hr>
<% if user_signed_in? %>
    <%= render 'comments/form', comment: @comment %>
<% end %>
<%= render @comments %>