config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  match '/ratings/article', to: 'ratings#article', via: :post
  match '/ratings/comment', to: 'ratings#comment', via: :post

  devise_for :users, path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  get 'welcome/index'
  resources :users, only: [:show, :index] do
    member do
      get :subscriptions, :subscribers
    end
  end
  resources :subscriptions

  root 'welcome#index'

  resources :articles do
    resources :comments
  end

  mount Sidekiq::Web, at: '/sidekiq'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : "Blog" %></title>
  <%= csrf_meta_tags %>

  <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
  <!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
  <![endif]-->

  <%= stylesheet_link_tag "application", :media => "all" %>

  <!-- For third-generation iPad with high-resolution Retina display: -->
  <!-- Size should be 144 x 144 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

  <!-- For iPhone with high-resolution Retina display: -->
  <!-- Size should be 114 x 114 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

  <!-- For first- and second-generation iPad: -->
  <!-- Size should be 72 x 72 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

  <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
  <!-- Size should be 57 x 57 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

  <!-- For all other devices -->
  <!-- Size should be 32 x 32 pixels -->
  <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

  <%= javascript_include_tag "application" %>

  <!-- custom scripts -->
  <%= stylesheet_link_tag "sweet-alert" %>
  <%= javascript_include_tag "sweet-alert.min" %>
</head>
<body>

<div class="navbar navbar-default navbar-static-top">
  <div class="container">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="/">Habrablog</a>

    <div class="navbar-collapse collapse navbar-responsive-collapse">
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
            <li><%= link_to 'Home', articles_path %></li>
            <li><%= link_to 'Members', users_path %></li>
        <% else %>
            <li><%= link_to 'Sign In', new_user_session_path %></li>
            <li><%= link_to 'Sign Up', new_user_registration_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-lg-9">
      <%= bootstrap_flash %>
      <%= yield %>
    </div>
    <div class="col-lg-3">
      <div class="well sidebar-nav">
        <ul class="nav nav-list">
          <% if user_signed_in? %>
              <li class="nav-header">
                <a href="<%= user_path current_user %>">
                  <%= image_tag current_user.avatar.url(:medium), class: "img-circle", width: "40px", height: "40px" %>
                  <%= current_user.get_name %>
                </a>
              </li>
              <li><%= link_to 'New article', new_article_path %></li>
              <li><%= link_to 'Sign Out', destroy_user_session_path, :method => :delete %></li>

          <% else %>
              <li><%= link_to 'Sign In', new_user_session_path %></li>
              <li><%= link_to 'Sign Up', new_user_registration_path %></li>
          <% end %>
        </ul>
      </div>
      <!--/.well -->
    </div>
    <!--/span-->
  </div>
  <!--/row-->

  <hr/>
  <footer>
    <%= debug(params) if Rails.env.development? %>
    <p>&copy; Company <%= Date.current().year() %></p>
  </footer>

</div>
<!-- /container -->

</body>
</html>

app/views/layouts/application_old.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>